import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CUBE 45",
  description: "Generated by create next app",
  other: {
    "google-site-verification": "fl1oJTclpVYY8GZk7eVsAhXSGgkj4HcIj41t_uNjE8c",
    "naver-site-verification": "8e714679c798e5d92aecb7e50b2f5ba23b5f9ce3"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
